schema_version = "1.0.0"

id = "cobe_blender"
version = "0.1.0" 
name = "CobeBlender"
tagline = "Перенастраивает Blender для работы с модом 'cobe'"
maintainer = "xz"
type = "add-on"

blender_version_min = "5.0.0"

license = [
    "SPDX:GPL-3.0-or-later",
]

tags = [
    "Animation",
    "Rigging",
    "Import-Export",
    "Pipeline",
    "User Interface"
]